import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script"; // Import the Script component

export const metadata: Metadata = {
  title: "Fairpro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-17700057645"
          strategy="afterInteractive"
        />
        <Script id="google-tag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17700057645');
          `}
        </Script>

        {/* */}
        <Script id="google-tag-conversion" strategy="afterInteractive">
          {`
            function gtag_report_conversion(url) {
              var callback = function () {
                if (typeof(url) != 'undefined') {
                  window.location = url;
                }
              };
              gtag('event', 'conversion', {
                  'send_to': 'AW-17700057645/7mgnCMGsor0bEK3khfhB',
                  'value': 10.0,
                  'currency': 'INR',
                  'event_callback': callback
              });
              return false;
            }
          `}
        </Script>
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
